---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
  DB_USER: Z2VuZXNpcw==
